services:
  db:
    image: postgres:16
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: python_api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydb
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pg_data: